spring:
  data:
    rest:
      base-path: /api

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  web:
    resources:
      static-locations: classpath:/static/

  mvc:
    static-path-pattern: /static/**

file:
  upload-dir: classpath:upload/

